---
- name: Check if auth_jwt directive is set in limit_except block (off)
  when:
    - _limit_except_block.auth_jwt is defined
    - _limit_except_block.auth_jwt.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        limit_except ({{ _limit_except_block.methods | join(' ') }}) {"
    line: "            auth_jwt off;"
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_off_directive

- name: Verify auth_jwt directive is set in limit_except block (off)
  when:
    - _limit_except_block.auth_jwt is defined
    - _limit_except_block.auth_jwt.off | default(false)
  ansible.builtin.assert:
    that:
      - not _auth_jwt_off_directive.changed
    fail_msg: auth_jwt directive is not set in limit_except block.
    success_msg: auth_jwt directive is set in limit_except block.

- name: Check if auth_jwt directive is set in limit_except block
  when:
    - _limit_except_block.auth_jwt is defined
    - not _limit_except_block.auth_jwt.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        limit_except ({{ _limit_except_block.methods | join(' ') }}) {"
    line: >-
      {{ '            ' }}auth_jwt {{ _limit_except_block.auth_jwt.realm -}}
        {{- ' token=' + _limit_except_block.auth_jwt.token | string if _limit_except_block.auth_jwt.token is defined }};
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_directive

- name: Verify auth_jwt directive is set in limit_except block
  when:
    - _limit_except_block.auth_jwt is defined
    - not _limit_except_block.auth_jwt.off | default(false)
  ansible.builtin.assert:
    that:
      - not _auth_jwt_directive.changed
    fail_msg: auth_jwt directive is not set in limit_except block.
    success_msg: auth_jwt directive is set in limit_except block.

- name: Check if auth_jwt_key_file directive is set in limit_except block
  when:
    - _limit_except_block.auth_jwt_key_file is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        limit_except ({{ _limit_except_block.methods | join(' ') }}) {"
    line: "            auth_jwt_key_file {{ _limit_except_block.auth_jwt_key_file }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_key_file_directive

- name: Verify auth_jwt_key_file directive is set in limit_except block
  when:
    - _limit_except_block.auth_jwt_key_file is defined
  ansible.builtin.assert:
    that:
      - not _auth_jwt_key_file_directive.changed
    fail_msg: auth_jwt_key_file directive is not set in limit_except block.
    success_msg: auth_jwt_key_file directive is set in limit_except block.

- name: Check if auth_jwt_key_request directive is set in limit_except block
  when:
    - _limit_except_block.auth_jwt_key_request is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        limit_except ({{ _limit_except_block.methods | join(' ') }}) {"
    line: "            auth_jwt_key_request {{ _limit_except_block.auth_jwt_key_request }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_key_request_directive

- name: Verify auth_jwt_key_request directive is set in limit_except block
  when:
    - _limit_except_block.auth_jwt_key_request is defined
  ansible.builtin.assert:
    that:
      - not _auth_jwt_key_request_directive.changed
    fail_msg: auth_jwt_key_request directive is not set in limit_except block.
    success_msg: auth_jwt_key_request directive is set in limit_except block.

- name: Check if auth_jwt_type directive is set in limit_except block
  when:
    - _limit_except_block.auth_jwt_type is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        limit_except ({{ _limit_except_block.methods | join(' ') }}) {"
    line: "            auth_jwt_key_request {{ _limit_except_block.auth_jwt_type }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_type_directive

- name: Verify auth_jwt_type directive is set in limit_except block
  when:
    - _limit_except_block.auth_jwt_type is defined
  ansible.builtin.assert:
    that:
      - not _auth_jwt_type_directive.changed
    fail_msg: auth_jwt_type directive is not set in limit_except block.
    success_msg: auth_jwt_type directive is set in limit_except block.

- name: Check if auth_jwt_require directive is set in limit_except block
  loop: "{{ _limit_except_block.auth_jwt_require | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        limit_except ({{ _limit_except_block.methods | join(' ') }}) {"
    line: >-
      {{ '            ' }}auth_jwt_require {{ item.values | join(' ') -}}
        {{- ' error=' + item.error | string if item.error is defined }};
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_require_directive

- name: Verify auth_jwt_require directive is set in limit_except block
  loop: "{{ _auth_jwt_require_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: auth_jwt_require directive is not set in limit_except block.
    success_msg: auth_jwt_require directive is set in limit_except block.
  loop_control:
    label: "{{ item.item }}"
